"""Initial migration

Revision ID: 2e1131f1fbe0
Revises: 
Create Date: 2026-02-16 16:15:25.981280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e1131f1fbe0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagram_cache',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('image_hash', sa.String(length=64), nullable=False),
    sa.Column('diagram_type', sa.String(length=50), nullable=True),
    sa.Column('original_path', sa.String(length=512), nullable=False),
    sa.Column('converted_path', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagram_cache_image_hash'), 'diagram_cache', ['image_hash'], unique=True)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('num_pages', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('current_stage', sa.String(length=100), nullable=True),
    sa.Column('upload_path', sa.String(length=512), nullable=True),
    sa.Column('result_path', sa.String(length=512), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    op.drop_index(op.f('ix_diagram_cache_image_hash'), table_name='diagram_cache')
    op.drop_table('diagram_cache')
    # ### end Alembic commands ###
